
FILES =     																	\
    src/pdfimport/Standalone.java                                                                                                               \
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/osm/OsmPrimitive.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/osm/DataSet.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/tools/I18n.java					\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/coor/LatLon.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/tools/Predicate.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/osm/DatasetCollection.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/osm/DataIntegrityProblemException.java	\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/osm/OsmPrimitiveType.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/osm/Storage.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/osm/PrimitiveId.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/osm/QuadBuckets.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/osm/Node.java					\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/osm/Way.java					\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/osm/Relation.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/osm/BBox.java					\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/osm/PrimitiveData.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/osm/Hash.java					\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/osm/Tagged.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/coor/QuadTiling.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/coor/CachedLatLon.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/coor/EastNorth.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/Bounds.java					\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/tools/CopyList.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/tools/Pair.java					\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/coor/Coordinate.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/projection/Ellipsoid.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/projection/Epsg4326.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/projection/Lambert.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/projection/LambertCC9Zones.java		\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/projection/LambertEST.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/projection/Mercator.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/projection/NTV2GridShift.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/projection/NTV2GridShiftFile.java		\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/projection/NTV2SubGrid.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/projection/NTV2Util.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/projection/Projection.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/projection/ProjectionSubPrefs.java		\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/projection/Puwg.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/projection/SwissGrid.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/projection/UTM.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/projection/UTM_France_DOM.java		\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/tools/GBC.java					\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/tools/CheckParameterUtil.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/coor/CoordinateFormat.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/osm/NameFormatter.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/osm/User.java					\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/osm/UserInfo.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/osm/WayData.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/osm/WaySegment.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/osm/RelationData.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/osm/RelationMember.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/osm/RelationMemberData.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/osm/RelationToChildReference.java		\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/osm/NodeData.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/osm/SimplePrimitiveId.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/osm/Tag.java					\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/osm/TagCollection.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/FileExporter.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/OsmWriter.java					\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/tools/DateParser.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/tools/DateUtils.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/XmlWriter.java					\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/osm/visitor/AbstractVisitor.java		\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/osm/visitor/AllNodesVisitor.java		\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/osm/visitor/BoundingXYVisitor.java		\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/osm/visitor/MergeSourceBuildingVisitor.java	\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/osm/visitor/Visitor.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/ProjectionBounds.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/tools/PrimaryDateParser.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/tools/FallbackDateParser.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/pdfimport/DuplicateNodesFinder.java					\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/pdfimport/FilePlacement.java						\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/pdfimport/LayerContents.java						\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/pdfimport/LayerInfo.java							\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/pdfimport/LoadPdfDialog.java						\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/pdfimport/OrthogonalShapesFilter.java					\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/pdfimport/OsmBuilder.java							\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/pdfimport/ParallelSegmentsFinder.java					\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/pdfimport/PathOptimizer.java						\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/pdfimport/PdfImportAction.java						\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/pdfimport/PdfImportPlugin.java						\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/pdfimport/PdfMultiPath.java						\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/pdfimport/PdfPath.java							\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/pdfimport/ProjectionInfo.java						\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/pdfimport/pdfbox/GraphicsProcessor.java					\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/pdfimport/pdfbox/PageDrawer.java						\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/pdfimport/pdfbox/PdfBoxParser.java					\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/pdfimport/pdfbox/operators/AppendRectangleToPath.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/pdfimport/pdfbox/operators/BeginInlineImage.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/pdfimport/pdfbox/operators/ClipEvenOddRule.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/pdfimport/pdfbox/operators/ClipNonZeroRule.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/pdfimport/pdfbox/operators/CloseFillEvenOddAndStrokePath.java		\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/pdfimport/pdfbox/operators/CloseFillNonZeroAndStrokePath.java		\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/pdfimport/pdfbox/operators/ClosePath.java					\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/pdfimport/pdfbox/operators/CurveTo.java					\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/pdfimport/pdfbox/operators/CurveToReplicateFinalPoint.java		\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/pdfimport/pdfbox/operators/CurveToReplicateInitialPoint.java		\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/pdfimport/pdfbox/operators/EndPath.java					\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/pdfimport/pdfbox/operators/FillEvenOddAndStrokePath.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/pdfimport/pdfbox/operators/FillEvenOddRule.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/pdfimport/pdfbox/operators/FillNonZeroAndStrokePath.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/pdfimport/pdfbox/operators/FillNonZeroRule.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/pdfimport/pdfbox/operators/Invoke.java					\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/pdfimport/pdfbox/operators/LineTo.java					\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/pdfimport/pdfbox/operators/MoveTo.java					\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/pdfimport/pdfbox/operators/SHFill.java					\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/pdfimport/pdfbox/operators/SetLineCapStyle.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/pdfimport/pdfbox/operators/SetLineDashPattern.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/pdfimport/pdfbox/operators/SetLineJoinStyle.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/pdfimport/pdfbox/operators/SetLineMiterLimit.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/pdfimport/pdfbox/operators/SetLineWidth.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/pdfimport/pdfbox/operators/StrokePath.java                                \
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/OsmExporter.java				\
    /mnt/data/home/mdupont/experiments/osm/josm/src/org/openstreetmap/josm/gui/layer/OsmDataLayer.java                                          \
    /mnt/data/home/mdupont/experiments/osm/josm/src/org/openstreetmap/josm/gui/layer/Layer.java                                          \


TEST =    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/APIDataSet.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/Preferences.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/ServerSidePreferences.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/Version.java					\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/osm/Changeset.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/osm/DataSource.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/osm/DatasetFactory.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/osm/Filter.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/osm/Filters.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/osm/OsmUtils.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/osm/PrimitiveDeepCopy.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/data/osm/TigerUtils.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/gui/layer/Layer.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/AllFormatsImporter.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/BoundingBoxDownloader.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/CacheCustomContent.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/CacheFiles.java					\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/Capabilities.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/ChangesetClosedException.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/ChangesetQuery.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/DefaultProxySelector.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/DiffResultProcessor.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/FileImporter.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/GpxExporter.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/GpxImporter.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/GpxReader.java					\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/GpxWriter.java					\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/IllegalDataException.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/JpgImporter.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/MirroredInputStream.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/MissingOAuthAccessTokenException.java		\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/MultiFetchServerObjectReader.java		\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/NMEAImporter.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/NmeaReader.java					\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/OsmApi.java					\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/OsmApiException.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/OsmApiInitializationException.java		\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/OsmApiPrimitiveGoneException.java		\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/OsmBzip2Exporter.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/OsmBzip2Importer.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/OsmChangeBuilder.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/OsmChangesetContentParser.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/OsmChangesetParser.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/OsmConnection.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/OsmDataParsingException.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/OsmGzipExporter.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/OsmGzipImporter.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/OsmHistoryReader.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/OsmImporter.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/OsmReader.java					\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/OsmServerBackreferenceReader.java		\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/OsmServerChangesetReader.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/OsmServerHistoryReader.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/OsmServerLocationReader.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/OsmServerObjectReader.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/OsmServerReader.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/OsmServerUserInfoReader.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/OsmServerWriter.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/OsmTransferCancelledException.java		\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/OsmTransferException.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/ProgressInputStream.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/auth/CredentialsManager.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/auth/CredentialsManagerException.java		\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/auth/CredentialsManagerFactory.java		\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/auth/CredentialsManagerResponse.java		\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/auth/DefaultAuthenticator.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/io/auth/JosmPreferencesCredentialManager.java	\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/plugins/Plugin.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/plugins/PluginDownloadException.java		\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/plugins/PluginDownloadTask.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/plugins/PluginException.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/plugins/PluginHandler.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/plugins/PluginInformation.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/plugins/PluginListParseException.java		\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/plugins/PluginListParser.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/plugins/PluginPreferenceFactory.java		\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/plugins/PluginProxy.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/plugins/ReadLocalPluginInformationTask.java	\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/plugins/ReadRemotePluginInformationTask.java	\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/tools/Base64.java					\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/tools/BugReportExceptionHandler.java		\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/tools/ColorHelper.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/tools/Destroyable.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/tools/ExceptionUtil.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/tools/ExifReader.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/tools/LanguageInfo.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/tools/MultiMap.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/tools/OpenBrowser.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/tools/OsmUrlToBounds.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/tools/PlatformHook.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/tools/PlatformHookOsx.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/tools/PlatformHookUnixoid.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/tools/PlatformHookWindows.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/tools/PresetTextComparator.java			\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/tools/Shortcut.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/tools/UrlLabel.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/tools/WikiReader.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/tools/WindowGeometry.java				\
    /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src/org/openstreetmap/josm/tools/XmlObjectParser.java				\



javac3 :
	javac -Xlint:unchecked -cp ./lib/pdfbox.jar $(FILES)


javac2 :
	javac -verbose $(FILES)


javac :
	javac -verbose -d /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/build -classpath /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/build -sourcepath /mnt/data/home/mdupont/experiments/osm/josm-plugins/pdfimport/src -target 1.6 -encoding UTF-8 -g  -Xlint:deprecation -Xlint:unchecked -source 1.6 $(FILES)

build2:
	ant -emacs 
# -debug -verbose

debug:
	ant -emacs -debug -verbose

clean:
	ant -emacs clean
# -debug -verbose
